### ISSUE TITLE
Manifest parse error

### ISSUE THREAD

**Issue by sengsational** [Liquidsoul/homebrew-formulae#1]
I installed `brew`, and it looks like that worked, but when I try `l10nconverter` it fails as follows:

> Further help:
  brew commands
  brew help [COMMAND]
  man brew
  https://docs.brew.sh
Dales-iMac:localizatino owner$ brew install liquidsoul/formulae/l10nconverter
==> Installing l10nconverter from liquidsoul/formulae
==> Cloning https://github.com/Liquidsoul/LocalizationConverter.git
Updating /Users/owner/Library/Caches/Homebrew/l10nconverter--git
==> Checking out tag 0.0.6
==> unset CC; make release
Last 15 lines from /Users/owner/Library/Logs/Homebrew/l10nconverter/01.unset:
2018-05-30 12:56:52 -0400
//
unset CC; make release
//
swift package clean
swift build --configuration release -Xswiftc -static-stdlib
/private/tmp/l10nconverter-20180530-83581-w2ko53: error: manifest parse error(s):
sandbox-exec: sandbox_apply_container: Operation not permitted
make: *** [.build/release/l10nconverter] Error 1
//
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/liquidsoul/homebrew-formulae/issues

**Comment by Liquidsoul** [comment]
Thanks for the report @sengsational 
I'll investigate.
Could you please give me the swift version used here by calling `swift --version`?
Thanks!

**Comment by Liquidsoul** [comment]
I found the issue and fixed it.

Seems like I now need to add the `--disable-sandbox` for the command home-brew uses to install (see https://github.com/mono0926/LicensePlist/issues/71#issuecomment-340457132).

I have pushed the `0.1.0` version with the fix.
You should now be able to install `l10nconverter` using `brew`.
Please feel free to reopen this issue if this does not fix your issue.
